name: Package

on:
  push:
    branches:
      - mac-store
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: 'mac'

    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install
        run: |
          pnpm install --no-frozen-lockfile

      - name: Set env
        if: matrix.platform == 'mac'
        run: |
          echo "APPLEID=${{ secrets.APPLEID }}" >> $GITHUB_ENV
          echo "APPLEIDPASS=${{ secrets.APPLEIDPASS }}" >> $GITHUB_ENV
          echo "CSC_LINK=${{ secrets.CERTIFICATE_OSX_APPLICATION }}" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.CERTIFICATE_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLETEAMID=${{ secrets.APPLETEAMID }}" >> $GITHUB_ENV
          echo "CSC_INSTALLER_LINK=${{ secrets.CSC_INSTALLER_LINK }}" >> $GITHUB_ENV
          echo "CSC_INSTALLER_KEY_PASSWORD=${{ secrets.CSC_INSTALLER_KEY_PASSWORD }}" >> $GITHUB_ENV
          echo -n "${{ secrets.PROVISION }}" | base64 --decode > build/bluestone.provisionprofile

      #      - name: ls
      #        run: |
      #          wget https://github.com/1943time/bs-web/releases/download/v0.5.1/dist.zip
      #          chmod 755 dist.zip
      #          unzip dist.zip
      #          mv -f dist web
      - name: Build
        run: |
          npm run build

      - name: Electron-Mac
        if: matrix.platform == 'mac'
        run: |
          npm run build:mac
#      - name: GH Release
#        uses: softprops/action-gh-release@v0.1.15
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          draft: false
#          prerelease: true
#          files: |
#            dist/Bluestone*.*
#            dist/latest*.yml
