name: WorkTest

on:
  push:
    branches: worktest
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: 'mac'

    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: download web program
        uses: suisei-cn/actions-download-file@v1.4.0
        with:
          url: "https://github.com/1943time/bs-web/releases/tag/v0.5.1/dist.zip"
      - name: ls
        run: |
          ls
          unzip -qq dist.zip -d web1
          ls
